name: PR CI

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  format-and-lint-check:
    name: Go format and lint check
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - name: Download modules
        run: go mod download

      - name: Formatting check (gofmt)
        run: |
          set -euo pipefail
          CHANGED=$(gofmt -l .)
          if [ -n "$CHANGED" ]; then
            echo "The following files need gofmt:" >&2
            echo "$CHANGED" >&2
            exit 1
          fi

      - name: Vet
        run: go vet ./...

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install lizard
        run: pip install --disable-pip-version-check --no-input lizard

      - name: Run lizard on main Lambda file only
        run: |
          # Check only the main file and fail on warnings
          # -C: cyclomatic complexity threshold (warn if function > 10)
          # -L: maximum function length (lines) threshold (warn if function > 120)
          lizard -l go -C 10 -L 120 internal/handler.go

      - name: Lizard csv output
        run: |
          lizard -l go -C 10 -L 120 internal/handler.go --csv          
